name: Dan Grimm
favicon: null
layout_spectrum: 0.36639
typography_spectrum: 0.14466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.11056410963647068
  lightness: 0.21744608017615974
  saturation: 0.4329387575853616
  rhythmicContrast: 0.9251470104791224
purpose: []
